site_name: Mobilit채tscheck f체r Magistratsvorlagen Dokumentation
site_url: https://mobilitaetcheck-fuer-magistratsvorlagen.gituhub.com
theme:
  name: material
nav:
  - Startseite: index.md
  - Einf체hrung:
      - Verwaltung: einfuehrung/verwaltung.md
      - Politik: einfuehrung/politik.md
      - B체rger: einfuehrung/buerger.md
  - Deployment:
      - Docker Compose: deployment/docker.md
      - Bare Metal: deployment/bare-metal.md
      - Umgebungsvariablen: deployment/env.md
  - Entwicklung: entwicklung.md
plugins:
  - include-markdown
